### ISSUE TITLE
DFA: dashboard visualization modules documentation

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_flow#117]
Related to #56  - document what visualization plots do.

AC:
- capture plot features in a doc (spreadsheet like this one https://docs.google.com/spreadsheets/d/1F7DYHe-z3-MKJ56Ce0g5WDaiqIklSFiLfLt4SnHuvMA/edit#gid=0 a google doc)
- capture visualization modules documentation in a format compatible with shiny-modules gallery

**Comment by lakikowolfe** [comment]
Features doc for modules - https://docs.google.com/spreadsheets/d/1TiY5oGjVNb6mReSF3SBUHnjCgpM4Qa2mPpUErWY7EFo/edit#gid=0
