### ISSUE TITLE
DFA: switch app to use HTAN datasets

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_flow#118]

**Comment by lakikowolfe** [comment]
AC:

- [ ] Generate HTAN Manifest (can be partial)
- [ ] Place manifest in a folder called `DataFlowStatus` in HTAN All Projects
- [ ] Adjust config to point to correct asset_view, manifest_dataset_id
- [ ] Run App to test

**Comment by lakikowolfe** [comment]
Generating HTAN manifest taking longer than expected. Running into connection problem with schematic that requires me to run each storage project separately.

**Comment by lakikowolfe** [comment]
Switching app to a more realistic situation surfaced a few problems:

- Highlight table is no longer working. Rows to highlight are identified by the `dataset_name` variable. To fix this need a more specific variable to match on (like synID?)
- Data Flow manifest contains multiple storage projects data...maybe only surface one storage project at a time on admin manifest view

**Comment by lakikowolfe** [comment]
#121 spun out from this ticket. Focusing on dashboard data viz this next sprint.
