### ISSUE TITLE
Match datasets on entityID not dataset_name

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_flow#121]
Keep entityID as a hidden column. Use this column to match datasets.

**Comment by milen-sage** [comment]
Related to #124

**Comment by lakikowolfe** [comment]
**AC:**

- [ ] Add entity ID to DataFlow schema
- [ ] Add entity ID to manifest generation script
- [ ] Regenerate HTAN skeleton manifest including entityIDs
- [ ] Add entity ID to config
- [ ] Test that app still runs
