### ISSUE TITLE
DFA: Research using authentication

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_flow#135]
Currently app is provided with a synapse token. Use authentication instead.

Authentication will open a login screen rather than relying on a provided token.

Look at DCA code for example

**Comment by milen-sage** [comment]
@lakikowolfe let's separate the research 

"Look at DCA code for example" so that you familiarize with the auth code steps.

for this sprint. 

Let's have the other items opened as separate issues for the next sprint.

**Comment by lakikowolfe** [comment]
_from anthony_
>DCA doesn't use a module for OAuth, but here is the relevant code in [ui.R](https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/ui.R#L211) and for [server.R lines 9-23](https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/server.R#L9)
however, dccvalidator and dccmonitor do use a [module for oauth](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/mod-synapse-oauth.R) you can see it in action in [app-ui.R](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/app-ui.R) and [app-server.R](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/app-server.R)

**Comment by milen-sage** [comment]
Thanks @lakikowolfe and @afwillia! It sounds like you have enough info and we can prioritize auth implementation for this sprint.

**Comment by lakikowolfe** [comment]
[Using OAuth2 with Shiny](https://gist.github.com/jcheng5/44bd750764713b5a1df7d9daf5538aea)
