### ISSUE TITLE
DFA: implement user authentication via OAuth

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_flow#142]
Currently the app does not recognize a user and doesn't check whether they have access to the necessary resources on Synapse.

AC: 

- [x] OAuth is implemented as researched in #135 
- [x] usrs see login, loading and authentication error screens as needed

**Comment by lakikowolfe** [comment]
Ended up using the project live approach to oauth. Reusing projectlive functions found in [`oauth_functions.R`](https://github.com/Sage-Bionetworks/projectlive.modules/blob/develop/R/oauth_functions.R)
