### ISSUE TITLE
DFA: setup shinyapps.io deployment workflows

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_flow#143]
Currently the app runs locally. We'd like to deploy it to shinyapps.io, initially as separate instances for each individual project (e.g. HTAN, INCLUDE). 

AC: 

- [x] the DFA is deployed using github workflows similar to the ones used for DCA
- [ ] three instances of the app are deployed: testing, staging and production

**Comment by milen-sage** [comment]
@lakikowolfe please feel free to reach out to @afwillia who's been documenting the deployment workflows and the necessary communication with the IT team.

**Comment by lakikowolfe** [comment]
#### Notes

- [DCA: shinyapps_deploy.md](https://github.com/Sage-Bionetworks/data_curator/blob/main/shinyapps_deploy.md)
- [shinyapps.io user guide](https://docs.posit.co/shinyapps.io/)

**Comment by milen-sage** [comment]
Related to #153

**Comment by lakikowolfe** [comment]
DFA is accessible at [https://sagebio.shinyapps.io/data_flow-staging/](https://sagebio.shinyapps.io/data_flow-staging/?_ga=2.160119800.41918623.1671574839-36591374.1671474916)

**Comment by milen-sage** [comment]
I see this message: 

An error has occurred

The application failed to start.

exit status 1

**Comment by milen-sage** [comment]
Ah nevermind I saw your comment on #153

**Comment by lakikowolfe** [comment]
Closing this issue and using #153 to track progress
