### ISSUE TITLE
DFA: deploy to shinyapps.io

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_flow#153]
Currently DFA is run locally, along with schematic running in the background to provide local REST API endpoints.

Deploy the app to shinyapps.io.

AC:

- [x] Get access to LastPass Sage shared folder
- [x] DFA is accessible via url on shinyapps.io
- [x] users are authenticated
- [x] DFA CI/CD github workflows are working
- [x] DFA shinyapps.io instance is configured to use max available memory; time out delay has been increased
- [ ] three instances of the app are deployed: testing, staging and production

**Comment by lakikowolfe** [comment]
### Notes from conversation with Anthony

- Ping SageIT for last pass credentials
- When you first push this to shiny.io it will create instance for you with whatever your app name will be
- In the GH action there is logic to manage different versions/instances of DCA, won't need this for DFA initially
- Once deployed log into the shinyapps dashboard and take a look
- Will likely need to change memory req (default is 1GB, DCA is set to 8GB)
- Takes about 15 min from push to deploy

**Comment by lakikowolfe** [comment]
DFA is accessible at [https://sagebio.shinyapps.io/data_flow-staging/](https://sagebio.shinyapps.io/data_flow-staging/?_ga=2.160119800.41918623.1671574839-36591374.1671474916)

**Comment by lakikowolfe** [comment]
App is deployed but not currently working.

- may need to update oauth creds?

**Comment by lakikowolfe** [comment]
App now loads 🥳

**Comment by lakikowolfe** [comment]
@milen-sage hm it looks like you're not able to retrieve the manifest

```
shinyapps[7924650]: Welcome, Milen Nikolov!
2023-01-03T20:27:31.521330+00:00 shinyapps[7924650]: No manifest available
```

I checked the folder sharing settings and you should have access

**Comment by lakikowolfe** [comment]
Tested the app on my end and the hiccups so far are:
- Milen unable to get manifest
- `model/submit` endpoint is not working. I have contacted Lingling and she said that this endpoint has not been tested yet. We are working towards a solution.
