### ISSUE TITLE
DFA: app deployment for INCLUDE

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_flow#158]
Deploy a test instance of the DFA app for INCLUDE on shinyapps.io

AC:
- DFA instance for INCLUDE is running similarly to the HTAN instance
- INCLUDE datasets are loaded with synthetic status

**Comment by lakikowolfe** [comment]
AC:

- [ ] Fork data_flow
- [ ] Set up new oauth credentials
- [ ] Add secrets to data_flow_INCLUDE
- [ ] Generate DFS manifest for INCLUDE
- [ ] Fill in DFS manifest with mock status data
- [ ] Point DFA at include data
- [ ] Set up branches (main, v0.0.0, and dev)
- [ ] Update settings in shinyapps.io dash
- [ ] Test that each instance works

**Comment by lakikowolfe** [comment]
repo: https://github.com/Sage-Bionetworks/data_flow_INCLUDE

shiny app: https://sagebio.shinyapps.io/data_flow_INCLUDE-staging/

**Comment by lakikowolfe** [comment]
Waiting on AWS rest API to come back online to test that this instance is up and working on shinyapps.io

**Comment by MiekoHash** [comment]
Hi @lakikowolfe , Do you know if we have an issue ticket somewhere tracking re AWS rest API being down?

**Comment by lakikowolfe** [comment]
@MiekoHash There isn't one in the DFA repo but maybe in schematic?

**Comment by MiekoHash** [comment]
Thanks, @lakikowolfe. From what I gathered in the tiger team's sprint planning meeting, I think it's https://sagebionetworks.jira.com/browse/DCA-74 and there are a few more related tickets.

**Comment by milen-sage** [comment]
@MiekoHash the issue is [DCA-73](https://sagebionetworks.jira.com/browse/DCA-73).

**Comment by MiekoHash** [comment]
cc: @abbywall for Project Board status update.

**Comment by MiekoHash** [comment]
Hi @lakikowolfe , DCA-73 is now resolved. Do we want to move this ticket to sprint 5 to be closed?

**Comment by lakikowolfe** [comment]
Sounds good to me!
