### ISSUE TITLE
DFA: create a new HTAN-specific instance

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_flow#159]
AC:

- [x] Fork data_flow
- [x] Set up new oauth credentials
- [x] Add secrets to data_flow_HTAN
- [x] Set up branches (main and dev)
- [x] Update settings in shinyapps.io dash
- [ ] Test that each instance works

**Comment by MiekoHash** [comment]
Hi @lakikowolfe , This ticket was brought up in today's D&T PM Standup as needing a follow-up. Is it correct to understand that this is one of the examples of "trailing issues from previous sprints" that will be completed in the subsequent sprint? I'm trying to have better understanding of the general issue by tying it to a ticket. Thanks in advance.

**Comment by lakikowolfe** [comment]
Yes this is a trailing ticket. I've been running into some issues getting the deployed instance to run without errors on start up

**Comment by lakikowolfe** [comment]
Switching from using projectlive.modules Oauth functions to using DCA implementation.

See #169

**Comment by MiekoHash** [comment]
Thanks, Loren. cc: @abbywall  for status update.

**Comment by lakikowolfe** [comment]
repo: https://github.com/Sage-Bionetworks/data_flow_HTAN

shiny app: https://sagebio.shinyapps.io/data_flow_HTAN-staging/
