### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_flow#43]
As brought up in #42 currently this app has no unit tests.

Start building out testing for this app

Resources:

- [TestThat Overview](https://testthat.r-lib.org/)
- [Mastering Shiny Ch. 21](https://mastering-shiny.org/scaling-testing.html)
- [projectLive tests](https://github.com/Sage-Bionetworks/ProjectLiveModules2/tree/develop/tests/testthat)
- [R Packages Ch. 13: Testing Overview](https://r-pkgs.org/testing-basics.html)

AC: app has > 50% unit test coverage.

**Comment by ychae** [comment]
Research timebox for sprint 13

**Comment by lakikowolfe** [comment]
#### Notes

- [`data_curator`](https://github.com/Sage-Bionetworks/data_curator/tree/schematic-rest-api/tests/testthat) focuses testing on API calls
- [`dcamodules`](https://github.com/Sage-Bionetworks/dcamodules/tree/main/tests/testthat) focuses on testing ui components
- [`projectlive`](https://github.com/Sage-Bionetworks/projectlive.modules/tree/develop/tests/testthat) focuses on testing package functions and modules

**Comment by milen-sage** [comment]
@lakikowolfe outline modules to start with here

AC:...

**Comment by lakikowolfe** [comment]
#### Select Storage Project

- [ ] `storage_projects()`
- [ ]  `list_to_dataframe()`

#### Select Dataset

- [ ] `storage_project_datasets()`

####  Datatable Dashboard

- [ ] Create testing config
- [ ] Use testing config to check parsing functions

#### Submit Model

- [ ] `model_submit`

#### General

- [ ] `manifest_string_to_date()`
- [ ] `manifest_date_to_string()`

**Comment by lakikowolfe** [comment]
Writing tests for `manifest_date_to_string` and `manifest_string_to_date` showed me that the functions could be improved. I want to generalize the parts of the function that update column type and build out some functions that manipulate the synapse manifest into the various forms needed for dfa.

Work will be tracked here #127
