### ISSUE TITLE
Rework administration back end

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_flow#51]
submit to dataFlowStatus manifest instead of updating the metadata manifest

allow for user to update release_scheduled, embargo, data_portal, released

- #60 
- #57 
- #17 
- #67
- #68
- #69

**Comment by lakikowolfe** [comment]
Work that spun out from this ticket:

- #60 
- #57

**Comment by ychae** [comment]
Draft PR here: https://github.com/Sage-Bionetworks/data_flow/pull/61
