### ISSUE TITLE
DFA: handling for when dataset is missing from Data Flow manifest

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_flow#64]
Scenario: A dataset has been added to a storage project but has not yet been included in the DataFlow manifest. I.e. 

_edit [03/06]_

"As a data manger, when a new dataset folder is added to a DCC, I want to see this dataset status independent of whether the dataset contains data or not"

Moving forward with using AWS batch to run job ([see IT service catalogue for more info](https://help.sc.sageit.org/sc/Service-Catalog-Provisioning.938836322.html#ServiceCatalogProvisioning-ScheduledJobs))

AC:

- [x] Write R script that pulls all datasets, compares to dfs manifest, and updates manifest with missing datasets
- [x] Contact IT about AWS creds (setting up an EC2 account)
- [x] Containerize script
- [x] Follow steps to use AWS batch to run script on a set schedule
- [x] Dataset should appear in DFA w/in 20 minutes from addition

**Comment by lakikowolfe** [comment]
Current workflow would force the user to manually update the data flow status manifest outside of the DFA UI.

**Comment by lakikowolfe** [comment]
#### Discussed in code review today

Possible solutions:

- DFA Administrator would be able to catch when a new dataset has been selected (no match in DFS manifest). When a new dataset is identified add a row to DFS manifest that has filled in contributor, dataset, dataset name, and num items for the row + any other selections from the update data flow status module. 
- Cron job that runs periodically, pulls down all datasets and compares to previously downloaded manifest. If a new dataset is identified, update manifest and submit back to synapse.

**Comment by lakikowolfe** [comment]
Moving forward with Cron Job idea

- pull all datasets
- compare synid to dfs manifest

Talk to DPE about this. They may have infrastructure to run periodic tasks.

**Comment by milen-sage** [comment]
Related #154

**Comment by lakikowolfe** [comment]
Notes for sprint planning:

- FAIR demo is up and running successfully. Manifest is updated every ten minutes.
- INCLUDE is up but not running successfully. It runs locally so I need to run down where the error is. Possibly need to make sure the docker image has correct version of dataflow package
- HTAN running into consistent errors locally. I think it might be disconnecting from server due to the many api calls being made.

**Comment by lakikowolfe** [comment]
Today all three scheduled jobs are running successfully.

INCLUDE and Demo run every ten minutes. HTAN is running once a day for now.
