### ISSUE TITLE
connect dashboard to schematic api endpoint

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_flow#65]
Currently dashboard is using mock up data. Replace mock up data with schematic api call retrieving dashboard.

AC:

- Dashboard displays data flow status manifest retrieved from synapse in dashboard

**Comment by ychae** [comment]
This is dependent on #51

**Comment by lakikowolfe** [comment]
Based on discussion in 1:1 with Milen on 8/31:

We discussed some options for where the dfs manifest will live. 

1. Each project could have its own data flow status manifest. Would have to retrieve and merge all of these manifests to display on dataset dashboard.
2. Data flow status manifest lives in asset_view and contains information from all storage projects within asset view. 

We decided on the second option going forward.

However I'm running into an issue where with the current endpoint set up I am unable to retrieve the dataset_id required to download/submit a manifest. To retrieve the manifest ID I've been using the `storage/project/manifests` endpoint which requires a project_id. So it seems with the current set up manifest must be at the storage project level.

Current work flow
```
asset_view <- config$asset_view
token <- config$token

storage_projects <- storage_projects(asset_view = asset_view,
                                           input_token = token)

# must select a storage project id (storage_project_id)

storage_project_manifests <- storage_project_manifests(asset_view = asset_view, 
                                                    project_id = storage_project_id, 
                                                    input_token = token)

# retrieve manifest dataset_id (manifest_id) by using regex to get data flow status manifest

# use dataset_id to download manifest (or submit)

manifest_download_to_df(asset_view =asset_view,
                                            dataset_id = manifest_id,
                                            input_token = token)
```

Is there a way to circumvent needing the project_id to get to dataset_id like getting all manifests for an asset view?

**Comment by lakikowolfe** [comment]
@milen-sage I have some questions about the implementation of the data flow manifest location that we talked about yesterday (see comment above). Lets plan on meeting tomorrow to discuss.

**Comment by lakikowolfe** [comment]
From meeting with milen:

- For now we only need to consider multi-tenant
- Put `asset_view` and data flow status `dataset_id` in config and source from there to avoid multiple API calls.

**Comment by lakikowolfe** [comment]
### Notes:

- `manifest/download` converts manifest columns all to string.
- This is breaking downstream manipulation of the manifest
- Need to create a function that checks the column types of each required column and ensures they are correctly coded + removes / hides columns that aren't included in the config.
