### ISSUE TITLE
DFA: update app styles to match DCA

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_flow#82]
Currently the DFA uses default shiny apps styles. Let's reuse the styles @rrchai has developed for the DCA. This would make the FAIR Data apps visually consistent. We can modify the DFA style later as needed.

@lakikowolfe the stying module @rrchai has developed may be a good application here.

**Comment by milen-sage** [comment]
AC: DCA styles are applied to the DFA.

**Comment by lakikowolfe** [comment]
replaces #14

**Comment by lakikowolfe** [comment]
Notes from meeting with Rong:

- Use `dcamodules::use_dca()` to implement styling. Place this anywhere in dashboardBody
- Currently only theme option is 'sage'. Rong will add more styling options
- Can create custom styling in `dcamodules::showcase()` saved to an rds file

**Comment by lakikowolfe** [comment]
Successfully able to use dcamodule function to update app styling.

![Screen Shot 2022-09-06 at 4 41 34 PM](https://user-images.githubusercontent.com/30699094/188758657-56600eac-11c0-413b-a36f-fc95d09718f2.png)

will update styling when rong creates new theme to match HTAN styles
