### ISSUE TITLE
Demo app with Adam and Ashley

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_flow#94]
When app is ready (user able to make multiple updates to manifest before submission + updated cells are highlighted

**Comment by lakikowolfe** [comment]
### Notes from meeting (11/17)

Discussed need to control who has access to the administration page
- Will need to be in control of who can update the data flow status manifest
- Maybe split into two apps? Or separate URLS?
- Ideally these groups will be controlled via synapse groups

Because Data Flow app only works at the whole manifest level, some things need to happen
- HTAN needs to wean off of the habit of uploading continually to a single manifeset
- Lock current manifests, do a data release that insures all files in a manifest are released and unreleased files are moved to a new manifest, educate on and document how to create and submit to a new manifest

More complex interactions between DCA / Synapse / DFA
- When a manifest has been moved to release need to be able to lock manifest in a way that doesn't crash DFA

Conditional compliance
- ex: if dataset is imaging require deidentification before release, if dataset is rna-seq don't require de-ID

Misc
- Can we notify people periodically of updates to data flow status (i.e. this month x many datasets have been released, etc)
- Bruno and team are working out validation right now link up to discuss output necessary for DFA
- Red / Green color scheme is not color blind friendly (icons, stacked bar colors)

**Comment by milen-sage** [comment]
Thanks for capturing the meeting summary @lakikowolfe !
